all: front_insert front_pop back_insert back_pop insert_anywhere ergodic
.PHONY: all
front_pop: front_pop.cpp
	g++ -o front_pop front_pop.cpp
front_insert: front_insert.cpp
	g++ -o front_insert front_insert.cpp
back_pop: back_pop.cpp
	g++ -o back_pop back_pop.cpp
back_insert: back_insert.cpp
	g++ -o back_insert back_insert.cpp
insert_anywhere: insert_anywhere.cpp
	g++ -o insert_anywhere insert_anywhere.cpp
ergodic: ergodic.cpp
	g++ -o ergodic ergodic.cpp